// ─────────────────────────────────────────────────────────────────────────────
//  MyAvatar.tsx — generated by Avatar Builder
//
//  Drop this single file into any React + TypeScript project.
//  Zero runtime dependencies — all SVG paths are baked in.
//
//  Avatar configuration snapshot
//    face      : Skin2Light
//    eyes      : Normal
//    mouth     : NormalSmile
//    hair      : Style03
//    accessory : RoundedGlasses
//    outfit    : Outfit23
//    backColor : #895fe6
// ─────────────────────────────────────────────────────────────────────────────

import React, { useRef, useEffect } from 'react';


// ─── Props ───────────────────────────────────────────────────────────────────
//
//  size          number   default 400    width & height in px
//  breathe       boolean  default true   Apple-like breathing loop
//  mouseFollow   boolean  default true   rAF-spring cursor parallax
//
//  Usage:
//    import { MyAvatar } from './MyAvatar';
//    <MyAvatar />
//    <MyAvatar size={300} />
//    <MyAvatar size={400} breathe={false} mouseFollow={false} />


// ─── Styles ──────────────────────────────────────────────────────────────────
//
//  All rules are scoped to .ab-* class names — they will not conflict with
//  styles already present in your project.
//
//  You can safely move these rules into your global stylesheet if you prefer
//  not to inject them at runtime via dangerouslySetInnerHTML.

const AVATAR_CSS = `
/* ─── Breathing animation ─────────────────────────────────────────────────────
 *
 * Values mirror the Avatar Builder's Motion animation exactly:
 *   translateY  0 → -4px → 0     (gentle upward float)
 *   rotateZ     0 →  1deg → 0    (subtle head tilt)
 *   scale       1 →  1.01 → 0    (slight swell)
 *   duration    4s  ·  easing: ease-in-out  ·  origin: bottom center
 * ─────────────────────────────────────────────────────────────────────────── */
@keyframes ab-breathe {
  0%, 100% { transform: translateY(0px)  rotateZ(0deg) scale(1);    }
  50%       { transform: translateY(-4px) rotateZ(1deg) scale(1.01); }
}

.ab-breathe {
  animation:        ab-breathe 4s ease-in-out infinite;
  transform-origin: bottom center;
  display:          inline-flex;
}

/* ─── Mouse-follow parallax ────────────────────────────────────────────────────
 *
 * The useMouseFollow hook writes --mx / --my (range −1 … 1) on the container.
 * Each layer multiplies those vars by its own depth offset so that moving the
 * cursor makes the avatar look around with a convincing sense of 3-D depth.
 *
 * To tune a layer: change its px multipliers below.
 * To disable all:  remove the 'ab-follow' class from the wrapper div.
 * ─────────────────────────────────────────────────────────────────────────── */
.ab-follow svg { overflow: visible; }

/* front → back depth order */
.ab-follow g[data-part='eyes']  { transform: translate(calc(var(--mx, 0) * 12px), calc(var(--my, 0) *  8px)); }
.ab-follow g[data-part='nose']  { transform: translate(calc(var(--mx, 0) * 12px), calc(var(--my, 0) *  8px)); }
.ab-follow g[data-part='mouth'] { transform: translate(calc(var(--mx, 0) * 10px), calc(var(--my, 0) *  7px)); }

/* face tilts on the X axis — transform-box + origin keep pivot centred */
.ab-follow g[data-part='face'] {
  transform:        translate(calc(var(--mx, 0) * 5px), calc(var(--my, 0) * 4px))
                    rotate(calc(var(--mx, 0) * 1.5deg));
  transform-box:    fill-box;
  transform-origin: 50% 50%;
}

.ab-follow g[data-part='hair']      { transform: translate(calc(var(--mx, 0) *  5px), calc(var(--my, 0) * 4px)); }
.ab-follow g[data-part='accessory'] { transform: translate(calc(var(--mx, 0) * 10px), calc(var(--my, 0) * 7px)); }
.ab-follow g[data-part='outfit']    { transform: translate(calc(var(--mx, 0) *  2px), calc(var(--my, 0) * 1px)); }
`;


// ─── useMouseFollow ───────────────────────────────────────────────────────────
//
//  Smooth rAF-based spring interpolation for cursor tracking.
//
//  Each animation frame:
//    1. Lerps (cx, cy) toward the raw cursor position (tx, ty).
//    2. Writes --mx / --my onto the container element as CSS custom properties.
//    3. The .ab-follow rules above multiply those vars per layer — no JS
//       needed at render time, making this completely jank-free.
//
//  LERP = 0.09 → relatively smooth.  Increase toward 1.0 for snappier tracking.

function useMouseFollow(
  ref:     React.RefObject<HTMLDivElement | null>,
  enabled: boolean,
) {
  useEffect(() => {
    const el = ref.current;
    if (!el || !enabled) return;

    let frameId: number;
    let cx = 0, cy = 0;   // current smoothed value
    let tx = 0, ty = 0;   // raw target from cursor
    const LERP = 0.09;

    const tick = () => {
      cx += (tx - cx) * LERP;
      cy += (ty - cy) * LERP;
      el.style.setProperty('--mx', cx.toFixed(4));
      el.style.setProperty('--my', cy.toFixed(4));
      frameId = requestAnimationFrame(tick);
    };

    const onMove = (e: MouseEvent) => {
      const { width, height, left, top } = el.getBoundingClientRect();
      tx = ((e.clientX - left) / width  - 0.5) * 2;
      ty = ((e.clientY - top)  / height - 0.5) * 2;
    };

    const onLeave = () => { tx = 0; ty = 0; };

    frameId = requestAnimationFrame(tick);
    el.addEventListener('mousemove',  onMove);
    el.addEventListener('mouseleave', onLeave);

    return () => {
      cancelAnimationFrame(frameId);
      el.removeEventListener('mousemove',  onMove);
      el.removeEventListener('mouseleave', onLeave);
    };
  }, [ref, enabled]);
}


// ─── AvatarSVG ───────────────────────────────────────────────────────────────
//
//  All paths are inlined — no external assets or imports required.
//  This block is machine-generated; treat it as a compiled artefact.

function AvatarSVG({ size }: { size: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 414 414" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Avatar Preview">
      <circle cx="207" cy="207" r="154" fill="#895fe6"/>
      <clipPath id="avatar-clip-r3">
        <circle cx="207" cy="207" r="154"/>
      </clipPath>
      <g clipPath="url(#avatar-clip-r3)">
        <g transform="translate(102.87255859375, 126.2861328125)">
          <g opacity="1">
            <g data-part="face">
              <svg xmlns="http://www.w3.org/2000/svg" width="193" height="243" fill="none">
                <path fill="#F7D3B5" d="M192.4 217.9c-.7.5-1.5 1-2.2 1.5-.8.5-1.5 1-2.3 1.4-.7.4-1.3.8-2 1.2-.1.1-.2.1-.3.2-2.3 1.4-4.7 2.7-7.1 3.9-.7.4-1.5.8-2.2 1.1 0 0-.1.1-.2.1l-2.4 1.2c-1.6.8-3.3 1.5-4.9 2.2-.8.4-1.7.7-2.5 1s-1.7.7-2.5 1-1.7.7-2.5 1h-.1c-.8.3-1.7.6-2.5.9-1.8.6-3.7 1.2-5.5 1.8-.6.2-1.3.4-1.9.6q-2.85.9-5.7 1.5c-.7.2-1.4.3-2.2.5-1.8.4-3.7.8-5.5 1.2-.4.1-.7.1-1.1.2-.6.1-1.3.2-1.9.3-.9.1-1.7.3-2.6.4-.4.1-.8.1-1.2.2-.5.1-1.1.2-1.7.2-1.6.2-3.3.4-4.9.6-.5.1-1.1.1-1.6.2h-.1c-.7.1-1.4.1-2.1.2s-1.4.1-2.1.1c-.4 0-.9.1-1.3.1-.8 0-1.5.1-2.2.1-1 0-1.9.1-2.9.1h-5C65.1 242.3 27.1 224.4.1 196c0 0 0-.1-.1-.1 3.1-6.1 14.6-17.1 26.6-26.2 15.2-11.5 36.7-18.6 36.7-18.6s14.1-2.3 66.4 8.6c39.9 8.4 56.9 42.5 62.7 58.2"/>
                <path fill="#F7D3B5" d="M140.801 187.4c-2.1 10.3-15.7 16.4-38.6 7.2-28.1-11.4-38.9-43.5-38.9-43.5-1.5-23-5-42.7-5-42.7 32.5-2.8 70.9 35.2 70.9 35.2l4.4 18.8c.4 1.6 1.2 3 2.4 4 2.1 3.6 6.2 14.4 4.8 21"/>
                <path fill="#EFBDA5" d="M135.999 166.501c-19.1-1-33.2-3.8-48.3-30.9 12.8 11.3 27.9 15.6 43.8 17.6l2.1 9.2c.4 1.7 1.2 3.1 2.4 4.1"/>
                <path fill="#F7D3B5" d="M175.501 46c1.8 8.4 2.7 15.2-2.2 37.6s4.5 44.8-19.1 65.3c-15.9 13.8-43.7 16.4-65.9 1.3-7.5-5.1-14.4-12.2-20-21.5-4.4-7.3-9.5-14.2-15.2-20.5-7.9-8.6-17.4-25.9-12.7-56.5 7.6-49.8 56.9-55.5 86-50s44.2 22.1 49.1 44.3"/>
                <path fill="#F7D3B5" d="M79.8 85.1s-3.1-15-17.7-13.2c-12.6 1.6-17 31.8 11.6 40.2"/>
                <path stroke="#423232" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="3" d="M72.8 98.4s-3.6-2.3-3.2-6.3c.6-4.7 0-7.6-2.2-8.5-5.5-2.3-6.6 4.1-6.4 4.9"/>
                <g data-part="nose">
                  <path fill="#EFBDA5" d="M149.101 108.1s3.8.2 7.4-4.1c2-2.4 3.7-5.4 2.6-6.3-1.1-1-19.2 1.8-20.4 4.2s5.8 6.2 10.4 6.2"/>
                  <path stroke="#423232" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="3" d="M152.1 74.5s.2 9.5 6.3 20.1c2.7 4.7-1.4 12.4-10.3 13.7"/>
                </g>
                <path fill="#ED938A" d="M97.9 113.2c5.688 0 10.3-3.805 10.3-8.5 0-4.694-4.612-8.5-10.3-8.5s-10.3 3.806-10.3 8.5c0 4.695 4.611 8.5 10.3 8.5M171.7 96.4c-.3 5.6-.2 11.1-.6 16.6-4.4-1-7.6-4.3-7.6-8.2 0-4.2 3.5-7.6 8.2-8.4" opacity="0.42"/>
              </svg>
            </g>
          </g>
        </g>
        <g transform="translate(203.1171875, 174.09765625)">
          <g opacity="1">
            <g data-part="eyes">
              <g>
                <svg viewBox="0 0 78 43" width="78" height="43" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path fill="#423232" d="M13.433 37.048c-2.4-.1-4.2-2.1-4-4.5l.1-2.8c.1-2.4 2.1-4.2 4.5-4 2.4.1 4.2 2.1 4 4.5l-.1 2.8c-.1 2.3-2.1 4.1-4.5 4M55.533 38.548c-2.2-.1-3.9-2-3.8-4.2l.1-2.6c.1-2.2 2-3.9 4.2-3.8s3.9 2 3.8 4.2l-.1 2.6c-.1 2.2-2 3.9-4.2 3.8"/>
                  <path stroke="#423232" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="3" d="M23.133 31.248s-2.6-3.7-7.1-4.4c-3.7-.6-7.8 1.2-8.4 3.3M52.633 32.147s0-3.2 4.6-3.2c3.8 0 5.4 3.5 5.4 3.5"/>
                  <path fill="#423232" d="M27.233 15.147c2.1.7 4.2-1.2 3.8-3.5-.2-1.2-.7-2.4-1.7-3.3-3-2.7-15.4-5.1-22.9-1.6-6.6 3.2 11.2 5.2 20.8 8.4M57.133 16.747c-1.7.6-3.5-1.2-3.2-3.3.1-1.1.5-2.2 1.3-3 2.4-2.4 10.6-4.3 15.8-.6 4.5 3.1-6.1 4-13.9 6.9"/>
                </svg>
              </g>
            </g>
          </g>
        </g>
        <g transform="translate(220.32513427734375, 239.43896484375)">
          <g opacity="1">
            <g data-part="mouth">
              <svg viewBox="0 0 30 16" width="30" height="16" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path stroke="#423232" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="3" d="M25.5 10C19.8 13.4 9.7 9.7 5 4"/>
              </svg>
            </g>
          </g>
        </g>
        <g transform="translate(85.10601806640625, 104.50048828125)">
          <g opacity="1">
            <g data-part="hair">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 194" width="250" height="194" fill="none">
                <path fill="#423232" d="M152.166 170.106c7.3-1.9 13.8-5.2 19.1-9.8 23.6-20.4 14.2-42.9 19.1-65.3 1.6-7.2 2.5-12.8 3.1-17.3-.8-.1-1.7-.2-2.6-.4-3.6-.5-6-3.8-5.6-7.4.2-1.5.3-3 .4-4.6-.4-.1-.3-.1-.7-.1-.6 1.9-1.3 3.9-1.8 5.8-.9 3-3.8 4.9-6.8 4.7h-.1c-3.5-.3-6.1-3.2-6.1-6.7.1-2.5.1-5 .2-7.5-.4-.1-.2 0-.6-.1-.5 2.6-1 5.2-1.5 7.9-.6 3.3-3.5 5.6-6.8 5.4-8.6-.4-17.1-.5-24.8-.5-3.4 0-6.2-2.5-6.5-5.9-.5-4.4-1.2-8.8-2.4-13.3-1.3 4-1.3 8.2-1.1 12.5.2 3.7-2.7 6.8-6.4 6.9-8.9.2-14.9.5-15.9.6.3 13.7-2.8 28.9-8.3 18.6-.4-.7-.7-1.4-1.1-2.3-2.3-4.1-6.9-9-15.6-7.9-12.2 1.6-16.7 29.9 8.9 39.3.1 2.1.6 4.2 1.5 6.4 3.9 9.5 5.6 17.4 5.6 23.9 0 37.7-61.7 22-79.1-12.2-6.7-13.3-6.8-29.3 5.9-46.1 31.1-38.1 21.8-23.6 28.7-46.2 11.3-37 37.1-48.8 71.3-48.5 0 0 56.9 0 72 13.8s9.9 56.9 8.6 60.8c-.4 1.2-1.4 1.9-2.5 2.4-.6 19.7 1.4 26.6 8.4 42.5 15.3 35-13.6 68.3-56.5 50.6"/>
                <path fill="#FEE4BF" d="M96.067 93.705c-.4-.7-.7-1.4-1.1-2.3.4.8.8 1.6 1.1 2.3"/>
              </svg>
            </g>
          </g>
        </g>
        <g transform="translate(70.3125, 250.3779296875)">
          <g opacity="1">
            <g data-part="outfit">
              <svg xmlns="http://www.w3.org/2000/svg" width="303" height="190" fill="none">
                <path fill="#FFD6C2" d="M203.006 48.8c-7.6-6.9-17.6-15-33.8-19.2-17.9-4.7-27.2 5.4-41.5 4-7.7-.8-20.3-15.8-28.8-13.6-10.5 2.8-22.1 8.4-36.1 18.1-3 2.1-28.7 19.3-37.6 47.4-8.1 25.4-10.1 60.4-10.3 72h227.8c.1-71.8-31.8-101.5-39.7-108.7"/>
                <path fill="#FFD6C2" d="M95.606 31.8s-1.9-16.6-.2-21.9c.2-.7 2.3-1.9 2.3-1.9s0 9.3 22.5 15.7c23.7 6.7 50.1 4.7 55 2.6 0 0 .1 13.8-2.5 19-4 8-35.8 6.3-55.1-.3-16.9-5.8-22-13.2-22-13.2"/>
                <g opacity="0.25">
                  <path stroke="#6D5F5E" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="5.009" d="M2.506 44.4c20.3-11.2 17.6.4 47.1-5.3 12.6-2.4 26.8-13.4 44.9-14.2 13.8-.6 29.1 8.6 46.1 9.8 14.2 1 30.6-6.3 47-3.6 14.3 2.3 27.5 14.3 43.5 18.2" opacity="0.25"/>
                  <path stroke="#6D5F5E" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="5.009" d="M2.906 55.8c21.9-9.1 18.4 2.4 48.4-2.5 13.1-2.1 27.9-13.2 46.2-14 14.3-.6 30 8.7 47.3 9.6 14.7.8 31.3-7.1 48-4.8 14.8 2 28.7 14 45 17.5" opacity="0.25"/>
                  <path stroke="#6D5F5E" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="5.009" d="M3.307 67.2c23.2-7.2 19 4.1 49.6.1 13.5-1.8 28.9-12.9 47.5-13.7 14.7-.6 31 8.9 48.5 9.6 15.2.6 32-7.9 49.1-6 15.3 1.7 29.9 13.6 46.6 16.6" opacity="0.25"/>
                  <path stroke="#6D5F5E" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="5.009" d="M3.705 78.6c24.3-5.4 19.6 5.7 50.8 2.5 14-1.5 30-12.6 48.9-13.3 15.2-.6 31.9 9.2 49.8 9.6 15.7.4 32.8-8.6 50.2-7.1 15.9 1.4 31.2 13.1 48.2 15.7" opacity="0.25"/>
                  <path stroke="#6D5F5E" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="5.009" d="M4.006 90.1c25.2-3.9 20.1 7.2 51.8 4.7 14.5-1.1 31.1-12.3 50.3-12.9 15.7-.5 32.9 9.5 51 9.8 16.2.2 33.6-9.3 51.3-8.2 16.4 1 32.5 12.6 49.9 14.6" opacity="0.25"/>
                  <path stroke="#6D5F5E" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="5.009" d="M4.205 101.6c26-2.5 20.6 8.5 52.8 6.8 15-.8 32.2-11.9 51.8-12.3 16.2-.4 33.8 9.9 52.3 10 16.7.1 34.5-10 52.4-9.2 17.1.7 33.9 12.1 51.5 13.4" opacity="0.25"/>
                  <path stroke="#6D5F5E" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="5.009" d="M4.506 113.2c26.7-1.2 21 9.7 53.9 8.8 15.4-.4 33.3-11.5 53.3-11.8 16.7-.2 34.8 10.3 53.6 10.3 17.3 0 35.4-10.5 53.6-10.2 17.7.3 35.3 11.5 53.2 12.2" opacity="0.25"/>
                  <path stroke="#6D5F5E" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="5.009" d="M4.705 124.7c27.4-.1 21.4 10.9 54.9 10.7 15.9-.1 34.4-11.1 54.8-11.2 17.2-.1 35.7 10.8 54.9 10.8 17.9-.1 36.3-11.1 54.8-11.2 18.4-.1 36.8 10.8 54.9 10.8" opacity="0.25"/>
                  <path stroke="#6D5F5E" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="5.009" d="M4.906 136.2c28.1.9 21.8 11.9 55.9 12.5 16.3.3 35.5-10.7 56.3-10.5 17.7.1 36.7 11.4 56.2 11.3 18.5-.1 37.2-11.6 56-12 19-.4 38.3 10.2 56.5 9.3" opacity="0.25"/>
                  <path stroke="#6D5F5E" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="5.009" d="M5.105 147.8c28.7 1.9 22.2 13 56.9 14.3 16.8.6 36.7-10.3 57.8-9.9 18.3.3 37.6 12 57.5 11.8 19-.1 38.2-12 57.2-12.8 19.7-.8 39.9 9.5 58.2 7.7" opacity="0.25"/>
                  <path stroke="#6D5F5E" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="5.009" d="M5.307 159.4c29.3 2.7 22.5 13.9 57.9 15.9 17.2 1 37.8-9.8 59.3-9.2 18.8.5 38.6 12.6 58.8 12.4 19.6-.1 39.2-12.4 58.5-13.5 20.5-1.2 41.5 8.7 59.8 6.1" opacity="0.25"/>
                </g>
                <path fill="#423232" d="M66.906 36.1c3.9 4.4 19.9 23.5 25.6 45.1l12.9 2.1s-13.8-34.4-32.8-51.2c-.8-.7-2-.8-3-.4-.8.4-1.8 1.1-2.7 2.3-.6.7-.5 1.6 0 2.1M189.007 76.7s1.7-25.8-11.2-44c0 0 .8-.8 5.3 1.4 3.2 1.5 12.6 14.4 13.5 40.5.1 0-6.5 2.2-7.6 2.1"/>
                <path fill="#423232" d="M89.506 63.3s73.9 19.7 105.8-2.1c0 0 16.6 32.7 23.1 96.3h-142.4s11.6-15.3 13.5-94.2"/>
                <path fill="#fff" d="M103.005 87.7a4.8 4.8 0 1 0 0-9.6 4.8 4.8 0 0 0 0 9.6M191.805 80.1a4.2 4.2 0 1 0 0-8.4 4.2 4.2 0 0 0 0 8.4"/>
              </svg>
            </g>
          </g>
        </g>
        <g transform="translate(148, 174)">
          <g opacity="1">
            <g data-part="accessory">
              <svg viewBox="0 0 145 121" width="145" height="121" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill="#B7AEA9" d="M110.234 46.4s1.2 6.8 9.1 10.2c2 .8 4.1-.5 4.1-2.7-.1 0-12.7-6.7-13.2-7.5M91.234 30s6.4-6.4 9.6-7.1l-8.5 2zM48.535 46.4s3.7 8.4 14.8 10.4c11.1 2.1 21.2-5.9 25.9-19.3 0 0-3.8 12.4-19 14.7-15.1 2.5-21.7-5.8-21.7-5.8" opacity="0.6"/>
                <path fill="#DBC3ED" d="M66.434 1.5c-14.1 0-25.6 11.8-25.7 26.2 0 6.8 2.5 13 6.6 17.5l36.3-36.7c-4.5-4.4-10.5-7-17.2-7" opacity="0.29"/>
                <path fill="#C4ADD8" d="m83.634 8.5-36.3 36.7c4.6 5.1 11.1 8.2 18.3 8.2 13.9 0 25.3-11.5 25.7-25.8.2-7.5-2.8-14.3-7.7-19.1" opacity="0.23"/>
                <path fill="#DBC3ED" d="M124.935 1.5c-10.7 0-19.7 11.8-20.1 26.2-.2 5.8 1.1 11.1 3.3 15.4l31.7-31.4c-3.3-6.2-8.7-10.2-14.9-10.2" opacity="0.29"/>
                <path fill="#C4ADD8" d="m139.835 11.6-31.7 31.4c3.3 6.3 8.7 10.4 15 10.4 10.5 0 19.5-11.5 20.1-25.8.2-5.9-1.1-11.5-3.4-16" opacity="0.23"/>
                <path stroke="#4EC2DD" strokeLinecap="round" strokeLinejoin="round" strokeMiterlimit="10" strokeWidth="3" d="M91.335 27.7c-.3 14.3-11.8 25.8-25.7 25.8s-25-11.5-25-25.8c.1-14.4 11.6-26.2 25.7-26.2s25.4 11.8 25 26.2M143.234 27.7c-.6 14.3-9.6 25.8-20.1 25.8s-18.7-11.5-18.3-25.8c.4-14.4 9.4-26.2 20.1-26.2s18.9 11.8 18.3 26.2M40.934 24.9h-14.2M91.434 24.9s11.9-4.6 13.4 0"/>
              </svg>
            </g>
          </g>
        </g>
      </g>
    </svg>
  );
}


// ─── MyAvatar ─────────────────────────────────────────────────────────────────

export function MyAvatar({
  size        = 400,
  breathe     = true,
  mouseFollow = true,
}: {
  size?:        number;
  breathe?:     boolean;
  mouseFollow?: boolean;
}) {
  const ref = useRef<HTMLDivElement>(null);
  useMouseFollow(ref, mouseFollow);

  const classes = [
    mouseFollow ? 'ab-follow'  : '',
    breathe     ? 'ab-breathe' : '',
  ].filter(Boolean).join(' ');

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: AVATAR_CSS }} />
      <div
        ref={ref}
        className={classes}
        style={{ width: size, height: size, display: 'inline-block' }}
      >
        <AvatarSVG size={size} />
      </div>
    </>
  );
}
